# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09c473a06b8ccc27682a2dd363d43aa5bc82a2384825f5aaf29b7201e14bdfc8ed17f6c8e8607c1288b5963438eff80be1404f0409fca96a4bb3fddfce4a581a

test:
  secret_key_base: a83ac67fe40c0938c84d5d162e5889e2720561982a75bc9ce9966e368a277f8240e0a260d0cca93eaa8ba7397548b8ec0dda2bc7140021fa2efa5cd12dc064d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
